#!/bin/bash
# Скрипт для сборки релиза APK

flutter clean 

flutter pub get

flutter build apk --release

mv build/app/outputs/flutter-apk/app-release.apk Compass40.apk

echo "--- сборка завершена: $(date) ---" >> sizes-log
du -h --max-depth=1 /home/user/ | sort -rh >> sizes-log
du -h --max-depth=1 /home/user/.gradle | sort -rh >> sizes-log
du -h --max-depth=1 /home/user/.gradle/daemon | sort -rh >> sizes-log
du -h --max-depth=1 /home/user/.gradle/caches | sort -rh >> sizes-log
df -h .  >> sizes-log

