#!/bin/bash
cd /home/user/myapp/android
./gradlew --stop
cd /home/user/myapp

rm -rf /home/user/.gradle/daemon
rm -rf /home/user/.gradle/caches/build-cache-1
rm -rf /home/user/.gradle/caches/transforms-*
# +30сек rm -rf /home/user/.gradle/caches/8.12/transforms

THRESHOLD_MB=3500   # предел папки /home/user/.gradle/caches/8.12/transforms
find /home/user/.gradle/caches -maxdepth 3 -type d -name transforms | while read -r t; do
    size_mb=$(du -sm "$t" 2>/dev/null | awk '{print $1}')
    [ -z "$size_mb" ] && size_mb=0

    message="transforms: $t = ${size_mb} MB (порог ${THRESHOLD_MB})";
    if [ "$size_mb" -gt "$THRESHOLD_MB" ]; then
        echo -e "\033[0;31m$message\033[0m";
        echo -e "\033[0;31m  -> удаляю /home/user/.gradle/caches/8.12/transforms\033[0m"
        rm -rf "$t"
    else
        echo -e "\033[0;32m$message\033[0m";
    fi
done

# вызовет последуюющую очень долгую сборку но реально очистит место
# rm -rf ~/.gradle/caches
# find ~/.gradle/caches -type f -atime +0 -delete

rm -rf /home/user/myapp/build/app/outputs/apk/debug/app-debug.apk
rm -rf /home/user/myapp/build/app/outputs/apk/release/app-release.apk
rm -rf /home/user/myapp/build/app/outputs/flutter-apk/app-debug.apk


# Flutter clean при желании можно оставить
# flutter clean
# flutter pub get

df -h .