name: compass40
description: "Compass 40°"
publish_to: 'none'
version: 3.1.10
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.1

  gps_info:
    path: packages/gps_info
  my_compass:
    path: packages/my_compass
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  collection: ^1.19.1
  equatable: ^2.0.8
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
