#!/bin/bash

# Список всех файлов в нужном порядке
files=(
lib/controllers/map_anchor_manager.dart
lib/controllers/map_target_manager.dart
lib/screens/target_screen.dart
)

# Вывести все файлы
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        echo "============= $file ==="
#        cat -n "$file"
        cat "$file"
        echo ""
    else
        echo "=== $file (ФАЙЛ НЕ НАЙДЕН) ==="
        echo ""
    fi
done